import type { Metadata } from "next";
import "./globals.css";
import Nav from "./core/Nav";
import Footer from "./core/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/gtj8rpo.css" />
      </head>
      <body suppressHydrationWarning={true}>
        <div className="antialiased relative">
          <Nav />
          <main className="relative">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
