import type { Metadata } from "next";
import "./globals.css";
import Nav from "./core/Nav";
import Footer from "./core/Footer";
import PerformanceMonitor from "./components/PerformanceMonitor";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/gtj8rpo.css" />
        <link href="https://vjs.zencdn.net/8.23.4/video-js.min.css" rel="stylesheet" />
        <script src="https://vjs.zencdn.net/8.23.4/video.min.js"></script>
      </head>
      <body suppressHydrationWarning={true}>
        <div className="antialiased relative">
          <Nav />
          <main className="relative">
            {children}
          </main>
          <Footer />
          <PerformanceMonitor />
        </div>
      </body>
    </html>
  );
}
